name: Compile sing-box Geosite win-update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  compile-geosite-winupdate-srs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Necessary Tools
        run: |
          sudo apt install -y curl jq wget sed coreutils git

      - name: Install sing-box
        run: |
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y sing-box

      - name: Download Text
        run: |
          wget -O win-update.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/win-update.txt

      - name: Format Json
        run: |
          jq -n --rawfile domains win-update.txt '{"version": 1, "rules": [{"domain": ($domains | split("\n") | map(select(length > 0)))}]}' > win-update.json

      - name: Compile Source
        run: |
          sing-box rule-set compile --output geoip-winupdate.srs win-update.json

      - name: Prepare geosite Folder
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          sudo mkdir -p geosite
          sudo mv -f geoip-winupdate.srs geosite
          sudo chown -R $USER:$USER geosite
          sudo chmod -R 755 geosite

      - name: Push Files
        run: |
          echo "Force updating repository with local content..."
          git checkout -b Release
          sudo git add geosite
          git commit -m "Update Windows Update srs"
          git push --force origin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
